spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/kannanfsd/microservices-2.git"
          search-paths: "/config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
         # search-locations: "file:///C://Users//hp//easyfund"
         # search-locations: "classpath:/config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
encrypt:
  key: "$riH@ri510"
server:
  port: 8071
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true