server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  config:
    import:
      - "application_qa.yaml"
      - "application_prod.yaml"
  profiles:
    active:
      - "qa"
build:
  version: "1.3"
accounts:
  message: "Welcome to EasyFund accounts related local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "johndoe@easyfund.com"
  onCallSupport:
    - (555)555-1234
    - (555)523-1345