build:
  version: "3.2"
loans:
  message: "Welcome to Easyfund Loan QA API microservices"
  contactDetails:
    name: "Asa Ogane - Developer"
    email: "asaogane@learning.com"
  onCallSupport:
    - (333)525-5623
    - (333)858-7895