server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yaml"
      - "application_prod.yaml"
  profiles:
    active: "qa"
build:
  version: "5.3"
cards:
  message: "Cards related details contact to below"
  contactDetails:
    name: "Tina williams"
    email: "tinawilliams@easyfund.com"
  onCallSupport:
    - (123)445 5656
    - (123)446 7896