build:
  version: "3.1"
loans:
  message: "Welcome to Easyfund Loan Prod API microservices"
  contactDetails:
    name: "Binod Kumar - Developer"
    email: "binodkumar@learning.com"
  onCallSupport:
    - (777)525-5623
    - (777)858-7895