build:
  version: "100.1"
accounts:
  message: "Welcome to EasyFund accounts related local prod APIs"
  contactDetails:
    name: "Himesh - Developer"
    email: "{cipher}4883281c51e4fb29bcff7cc5241e50be995a63d823489fc9ac9cc878b7839c8f7a86dae2fdd3d18d3a349d64bffe4146"
  onCallSupport:
    - (222)555-1234
    - (222)523-1345
