build:
  version: "100.3"
accounts:
  message: "Welcome to EasyFund accounts related local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "johndoe@easyfund.com"
  onCallSupport:
    - (555)555-1234
    - (555)523-1345