build:
  version: "100.1"
accounts:
  message: "Welcome to EasyFund accounts related local prod APIs"
  contactDetails:
    name: "Himesh - Developer"
    email: "{cipher}a1d2dbce4727dbd17400fa146f10bc2ef06dc55816f5b7073f3bcb0ed16495c00cdf979baf31b9f2aa08c0963ae9ef99"
  onCallSupport:
    - (222)555-1234
    - (222)523-1345
