build:
  version: "500.1"
cards:
  message: "Cards related details contact to below Webhook API calls Microservice"
  contactDetails:
    name: "Remya Ramachandran"
    email: "andree@easyfund.com"
  onCallSupport:
    - (123)445 5656
    - (123)446 7896
