build:
  version: "501.3"
cards:
  message: "Cards related details contact with default webhook config"
  contactDetails:
    name: "Tina williams"
    email: "tinawilliams@easyfund.com"
  onCallSupport:
    - (123)445 5656
    - (123)446 7896
