build:
  version: "500.3"
cards:
  message: "Cards related details contact as below with default config"
  contactDetails:
    name: "Tina williams"
    email: "tinawilliams@easyfund.com"
  onCallSupport:
    - (123)445 5656
    - (123)446 7896
