build:
  version: "300.1"
loans:
  message: "Welcome to Easyfund Loan Production API microservices"
  contactDetails:
    name: "Binod Kumar - Developer"
    email: "binodkumar@learning.com"
  onCallSupport:
    - (777)525-5623
    - (777)858-7895
