build:
  version: "300.3"
loans:
  message: "Welcome to Easyfund Loan microservices"
  contactDetails:
    name: "David Mirchi - Developer"
    email: "davidmirchi@learning.com"
  onCallSupport:
    - (777)525-5623
    - (777)858-7895
